### ISSUE TITLE
MPL?

### ISSUE THREAD

**Issue by ghost** [RichardlL/Tunnul#1]
I am not good for license such things, simple MIT license please?

**Comment by RichardlL** [comment]
I'm not sure I understand. What are you trying to do?  

Under the MPL, You can use my code with any license you want (even proprietary), but if you modify it, you have to license it under MPLv2 or GPLv3. 

 If you would like to collaborate, I'm sure we could work we could easily work licensing out.

I saw @mindcat is part of PistonDevelopers, so
CC:
@bvssvni 
@toqueteos

**Comment by bvssvni** [comment]
One reason MIT is popular is because of static linking. Under some interpretations of GPLv3 dynamic linking is required when used with libraries using incompatible licenses.

**Comment by RichardlL** [comment]
@bvssvni @mindcat 

I know you can dynamic or static link to MPL, also, which is why I chose it.

You cant link to GPL3 at all unless its also GPL or compatible.

I think you mean LGPL, which you can dynamically link to.

Like I said, you can dynamically or statically link to MPL.

**Comment by bvssvni** [comment]
@RichardlL I didn't know that about MPL.

**Comment by RichardlL** [comment]
I'm not sure what @mindcat is interested in.  I assume she was interesting in using some of my code in Hematite/ Hematite's server. I completely O.K. with that, but its still under the MPL2, and is my copyright.

I have a lot of specific goals for my project, like what I said in https://github.com/PistonDevelopers/hematite/issues/203
And since my idea is to change the structure from the ground up, it would be hard to just to start contributing to another project. (such as hematite-server). It would be arrogant to take a project, restructure it, and then try to dictate over everyone else's contributions for all future progress, So I made my own*

She (and anyone else) is free to use any current or future progress as allowed under the MPL. I'm keeping it under that to hopefully prevent someone from hacking my project finished, then releasing a bad parody of it (see ublock).

**(I'm open to merging this with hematite server (and having it under whatever license).  Although, I would mostly have to be in charge of commits and pulls, so I could control of the project's structure, and meet my original goals)*

**Comment by mindcat** [comment]
@RichardlL It just about the longer license, nevermind about that.

**Comment by RichardlL** [comment]
@mindcat @bvssvni @toqueteos

Changed to BSD
